version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "05:00"
      timezone: "Africa/Casablanca"
    open-pull-requests-limit: 4
    labels:
      - deps
      - security
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"
    groups:
      dev-minor-patch:
        patterns:
          - "*"
        dependency-type: development
        update-types:
          - minor
          - patch

  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: monthly
      day: monday
      time: "06:00"
      timezone: "Africa/Casablanca"
    open-pull-requests-limit: 2
    labels:
      - deps
      - security
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-minor"
          - "version-update:semver-patch"
    groups:
      dev-majors:
        patterns:
          - "*"
        dependency-type: development
        update-types:
          - major

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: monthly
      day: monday
      time: "07:00"
      timezone: "Africa/Casablanca"
    open-pull-requests-limit: 2
    labels:
      - deps
      - security
    groups:
      actions-monthly:
        patterns:
          - "*"
