version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "05:00"
      timezone: "Africa/Casablanca"
    open-pull-requests-limit: 1
    labels:
      - dependencies
      - security
    cooldown:
      semver-major-days: 30
      semver-minor-days: 7
      semver-patch-days: 7
    groups:
      dev-minor-patch:
        patterns:
          - "*"
        dependency-type: development
        update-types:
          - minor
          - patch
      dev-majors:
        patterns:
          - "*"
        dependency-type: development
        update-types:
          - major

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: monthly
      day: monday
      time: "07:00"
      timezone: "Africa/Casablanca"
    open-pull-requests-limit: 1
    labels:
      - dependencies
      - security
    groups:
      actions-monthly:
        patterns:
          - "*"
